### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by jayurbain** [udacity/artificial-intelligence-for-trading#9]
Taking AI for Trading. This notebook does not even get past the first import cell. Change numpy to 1.14.5 get down to the alphaens block and it fails again.

**Comment by zjt2996998** [comment]
trying to take the first quiz  but
from tests import project_test, assert_output
is not working.
I tried to add # sys.path.append('/artificial-intelligence-for-trading/')
from tests import project_test, assert_output 
still not working.
